<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
$additionalClass = $block->getAdditionalClass();
$htmlId = $block->getBannerItemHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<div class="tigren-bannermanager slider <?= $additionalClass ?>">
    <style>
        .custom-navigation {
            display: table;
            width: 100%;
            table-layout: fixed;
        }

        .custom-navigation > * {
            display: table-cell;
        }

        .custom-navigation > a {
            width: 50px;
        }

        .custom-navigation .flex-next {
            text-align: right;
        }
    </style>
    <script type="text/javascript">
        require(['jquery', 'tigren/flexslider'], function ($) {
            $(document).ready(function ($) {
                var flexSliderSelector = '<?= $htmlId; ?>';
                $('.' + flexSliderSelector).flexslider({
                    animation: 'slide',
                    controlsContainer: $('.custom-controls-container'),
                    customDirectionNav: $('.custom-navigation a')
                });
            });
        });
    </script>
    <div class="tigren-bannermanager-slider">
        <div id="<?= $htmlId ?>" class="flexslider flexslider-content-image <?= $htmlId ?>"
             style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner): ?>
                    <li>
                        <a href="<?= $banner->getBannerUrl() ?>"
                           <?= $banner->getTarget() ? 'target="_blank" ' : ''; ?>style="display:block;">
                            <img alt="<?= $banner->getTitle() ?>"
                                 src="<?= $block->getBannerImageUrl($banner) ?>"
                                 title="<?= $banner->getDescription() ?>" />
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <div class="custom-navigation">
            <a href="#" class="flex-prev">Prev</a>
            <div class="custom-controls-container"></div>
            <a href="#" class="flex-next">Next</a>
        </div>
    </div>
</div>
