<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

use Magento\Framework\App\ObjectManager;

$objectManager = ObjectManager::getInstance();
$customer_session = $objectManager->create('Magento\Customer\Model\Session');
?>
<div class="mb-forgetpassword-popup" style="display:none;">
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-forgotpassword">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading"
                    aria-level="2"><?= $block->escapeHtml(__('Forgot Your Password')) ?></strong>
        </div>
        <form class="form ajax-forgetpassword-form"
              method="post"
              enctype="multipart/form-data" autocomplete="off">
            <fieldset class="fieldset" data-hasrequired="<?= __('* Required Fields') ?>">
                <div
                        class="field note"><?= __('To have your password reset, enter your email address below. We will then send an email containing a link to reset your password.'); ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?= __('Email') ?></span></label>
                    <div class="control">
                        <input type="email" name="email" alt="email" class="input-text email_address"
                               value="<?= $block->escapeHtml($block->getEmailValue()) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info'); ?>
            </fieldset>
            <div class="actions">
                <div class="">
                    <button type="submit" class="action submit primary"><span><?= __('Reset Password') ?></span>
                    </button>
                </div>
            </div>
            <?php if (!$customer_session->isLoggedIn()): ?>
                <div class="actions">
                    <div class="secondary">
                        <a class="action back" href="<?= $block->getLoginUrl() ?>">
                            <span class="mb-back-link"><?= __('Login') ?></span>
                        </a>
                    </div>
                    <span> | </span>
                    <div class="secondary">
                        <a class="action mb-create-account" href="<?= $block->getUrl('customer/account/create'); ?>">
                            <span><?= __('Create an Account') ?></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>