<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<div class="mb-register-popup" style="display:none;">
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-register">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading"
                    aria-level="2"><?= $block->escapeHtml(__('Create New Customer Account')) ?></strong>
        </div>
        <form class="form form-create-account mb-login-form-register"
              method="post"
              id="ajax-register-form"
              enctype="multipart/form-data" autocomplete="off">
            <fieldset class="fieldset create info">
                <legend class="legend"><span><?= __('Personal Information'); ?></span></legend>
                <br>
                <input type="hidden" name="success_url" value="">
                <input type="hidden" name="error_url" value="">
                <div class="field field-name-firstname required">
                    <label class="label" for="firstname">
                        <span><?= __('First Name') ?></span>
                    </label>
                    <div class="control">
                        <input type="text" id="firstname" name="firstname" value="" title="First Name"
                               class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <label class="label" for="lastname">
                        <span><?= __('Last Name') ?></span>
                    </label>

                    <div class="control">
                        <input type="text" id="lastname" name="lastname" value="" title="Last Name"
                               class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>

                <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1"
                           id="is_subscribed" class="checkbox">
                    <label for="is_subscribed" class="label"><span><?= __('Sign Up for Newsletter') ?></span></label>
                </div>

            </fieldset>
            <fieldset class="fieldset create account">
                <legend class="legend"><span><?= __('Sign-in Information') ?></span></legend>
                <br>
                <div class="field required">
                    <label for="customer-email" class="label"><span><span><?= __('Email') ?></span></span></label>
                    <div class="control">
                        <input type="email" name="email" autocomplete="email" id="customer-email" value="" title="Email"
                               class="input-text" data-validate="{required:true, 'validate-email':true}"
                               aria-required="true">
                    </div>
                </div>
                <div class="field password required">
                    <label for="password" class="label"><span><?= __('Password') ?></span></label>
                    <div class="control">
                        <input type="password" name="password" id="password" title="Password" class="input-text"
                               data-password-min-length="8" data-password-min-character-sets="3"
                               data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                               aria-required="true">
                    </div>

                </div>
                <div class="field confirmation required">
                    <label for="password-confirmation" class="label"><span><?= __('Confirm Password') ?></span></label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="Confirm Password"
                               id="password-confirmation" class="input-text"
                               data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
            </fieldset>
            <div class="actions mb-style-actions">
                <div class="primary">
                    <button type="submit" class="action submit primary"
                            title="Create Account"><span><?= __('Create an Account') ?></span></button>
                </div>
            </div>
            <div class="actions">
                <div class="secondary">
                    <a class="action forgot" href="<?= $block->getUrl('customer/account/forgotpassword'); ?>">
                        <span><?= __('Forgot Your Password?') ?></span>
                    </a>
                </div>
                <span> | </span>
                <div class="secondary">
                    <a class="action back" href="<?= $block->getUrl('customer/account/login'); ?>">
                        <span class="mb-back-link"><?= __('Login') ?></span>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>