<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php $_product = $block->getProduct(); ?>
<div class="mb-login-popup-title center">
    <div class="mb-login-popup-title">
        <strong><?= __('You failed to add product to the comparison list.'); ?></strong>
    </div>
</div>
<div class="ajaxcompare-success-box">
    <p class="message-error">
        <!--NOTHING-->
    </p>
    <h2 class="product-name"><?= $_product->getName() ?></h2>
    <?= $block->getChildHtml('product_image', true); ?>
    <div class="ajaxcompare-buttons">
        <button type="button" id="ajaxcompare_btn_close_popup" class="action primary mb-ajaxsuite-close"
                title="<?= __('Close') ?>">
            <span><?= __('Close ') ?></span>
            <?php
            if ($popupTTL = $this->helper('Tigren\Ajaxsuite\Helper\Data')->getTTLAjaxSuite()) {
                ?>
                (<span class="ajaxsuite-autoclose-countdown"><?= $popupTTL ?></span>)
                <?php
            }
            ?>
        </button>
        <button type="button" id="ajaxcompare_btn_to_login" class="action focus primary"
                title="<?= __('Login') ?>">
            <span><?= __('Login') ?></span>
        </button>
    </div>
</div>