<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

/** @var Js $block */

use Tigren\Ajaxlogin\Block\Js;

?>
<script type="text/x-magento-init">
{
    "*": {
        "tigren/ajaxlogin"    : <?= $block->getAjaxLoginInitOptions(); ?>
    }
}

</script>