<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
if ($block->isCustomerLoggedIn()) {
    ?>
    <div id="mb-ajaxlogin-wrapper">
        <?= $block->getChildHtml('ajaxlogin.popup.message'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.forgot'); ?>
    </div>
    <?php
} else {
        ?>
    <div id="mb-ajaxlogin-wrapper">
        <?= $block->getChildHtml('ajaxlogin.popup.login'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.register'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.forgot'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.message'); ?>
    </div>
    <?php
    }
