<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

?>
<div id="<?= $block->getHtmlId() ?>" class="admin__grid-massaction">

    <?php if ($block->getHideFormElement() !== true): ?>
    <form action="" id="<?= $block->getHtmlId() ?>-form" method="post">
        <?php endif ?>
        <div class="admin__grid-massaction-form">
            <?= $block->getBlockHtml('formkey') ?>
            <select
                    id="<?= $block->getHtmlId() ?>-select"
                    class="local-validation admin__control-select">
                <option class="admin__control-select-placeholder" value="" selected><?= __('Actions') ?></option>
                <?php foreach ($block->getItems() as $_item): ?>
                    <option value="<?= $_item->getId() ?>"<?= ($_item->getSelected() ? ' selected="selected"' : '') ?>><?= $_item->getLabel() ?></option>
                <?php endforeach; ?>
            </select>
            <span class="outer-span" id="<?= $block->getHtmlId() ?>-form-hiddens"></span>
            <span class="outer-span" id="<?= $block->getHtmlId() ?>-form-additional"></span>
            <?= $block->getApplyButtonHtml() ?>
        </div>
        <?php if ($block->getHideFormElement() !== true): ?>
    </form>
<?php endif ?>
    <div class="no-display">
        <?php foreach ($block->getItems() as $_item): ?>
            <div id="<?= $block->getHtmlId() ?>-item-<?= $_item->getId() ?>-block">
                <?= $_item->getAdditionalActionBlockHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="mass-select-wrap">
        <select
                id="<?= $block->getHtmlId() ?>-mass-select"
                class="action-select-multiselect"
                data-menu="grid-mass-select">
            <optgroup label="<?= __('Mass Actions') ?>">
                <option disabled selected></option>
                <?php if ($block->getUseSelectAll()): ?>
                    <option value="selectAll">
                        <?= __('Select All') ?>
                    </option>
                    <option value="unselectAll">
                        <?= __('Unselect All') ?>
                    </option>
                <?php endif; ?>
                <option value="selectVisible">
                    <?= __('Select Visible') ?>
                </option>
                <option value="unselectVisible">
                    <?= __('Unselect Visible') ?>
                </option>
            </optgroup>
        </select>
        <label for="<?= $block->getHtmlId() ?>-mass-select"></label>
    </div>
    <script>
        require(['jquery'], function ($) {
            'use strict';
            $('#<?= $block->getHtmlId() ?>-mass-select').change(function () {
                var massAction = $('option:selected', this).val();
                switch (massAction) {
                <?php if ($block->getUseSelectAll()):?>
                    case 'selectAll':
                        return <?= $block->getJsObjectName() ?>.
                        selectAll();
                        break;
                    case 'unselectAll':
                        return <?= $block->getJsObjectName() ?>.
                        unselectAll();
                        break;
                <?php endif; ?>
                    case 'selectVisible':
                        return <?= $block->getJsObjectName() ?>.
                        selectVisible();
                        break;
                    case 'unselectVisible':
                        return <?= $block->getJsObjectName() ?>.
                        unselectVisible();
                        break;
                }
                this.blur();
            });
        });

        <?php if (!$block->getParentBlock()->canDisplayContainer()): ?>
        <?= $block->getJsObjectName() ?>.setGridIds('<?= $block->getGridIdsJson() ?>');
        <?php endif; ?>
    </script>
</div>
