<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
$additionalClass = $block->getAdditionalClass();
$htmlId = $block->getBannerItemHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<div class="tigren-bannermanager random <?= $additionalClass ?>">
    <div class="tigren-bannermanager-slider">
        <div id="<?= $htmlId ?>" class="flexslider flexslider-content-image <?= $htmlId ?>"
             style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner): ?>
                    <li class="random">
                        <a href="<?= $banner->getBannerUrl() ?>"
                           <?= $banner->getTarget() ? 'target="_blank" ' : ''; ?>style="display:block;">
                            <img alt="<?= $banner->getTitle() ?>"
                                 src="<?= $block->getBannerImageUrl($banner) ?>"
                                 title="<?= $banner->getDescription() ?>" />
                        </a>
                        <?php if ($banner->getDescription()) : ?>
                            <p class="flex-caption"><?= $banner->getDescription() ?></p>
                        <?php endif; ?>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>
