<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
$_product = $block->getProduct();
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= $required; ?>>
    <div class="product-name"><?= $_product->getName() ?></div>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('product_price'); ?>
        <?= $block->getChildHtml('product_options'); ?>
        <?php if ($_product->getTypeId() === 'configurable'): ?>
            <?= $block->getChildHtml('type_options_configurable'); ?>
        <?php elseif ($_product->getTypeId() === 'bundle') : ?>
            <?= $block->getChildHtml('type_options_bundle'); ?>
        <?php elseif ($_product->getTypeId() === 'downloadable') : ?>
            <?= $block->getChildHtml('type_options_downloadable'); ?>
        <?php endif; ?>
        <?= $block->getChildHtml('html_calendar'); ?>
        <?= $block->getChildHtml('product_options_wrapper_bottom'); ?>
    </div>
</div>