<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2019 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
$successHeader = $this->helper(Tigren\Ajaxcart\Helper\Data::class)->getSuccessHeaderAjaxCart();
?>
<?php $_product = $block->getProduct(); ?>

<?php if ($successHeader): ?>
    <div class="mb-login-popup-title">
        <strong><?= $successHeader ?></strong>
    </div>
<?php endif; ?>
<div class="mb-ajaxsuite-popup-border ajaxcart-success-box">
    <div class="success-content">
        <?= $block->getChildHtml('ajaxcart.message'); ?>

        <h2 class="product-name"><?= $_product->getName() ?></h2>
        <?= $block->getChildHtml('product_option'); ?>
        <?= $block->getChildHtml('product_image'); ?>
        <?= $block->getChildHtml('ajaxcart.cartinfo'); ?>
        <?= $block->getChildHtml('ajaxcart.product.related'); ?>
    </div>
    <div class="ajaxcart-buttons ajaxsuite-buttons">
        <button type="button" id="ajaxcart_cancel" class="action primary mb-ajaxsuite-close"
                title="<?= __('Continue Shopping') ?>">
            <span><?= __('Continue Shopping ') ?></span>
            <?php
            if ($popupTTL = $this->helper('Tigren\Ajaxsuite\Helper\Data')->getTTLAjaxSuite()) {
                ?>
                (<span class="ajaxsuite-autoclose-countdown"><?= $popupTTL ?></span>)
                <?php
            }
            ?>
        </button>
        <button type="button" id="ajaxcart_checkout" class="action focus primary"
                title="<?= __('View Cart') ?>"
                onClick="window.location = '<?= $block->getUrl('checkout/cart'); ?>'">
            <span><?= __('View Cart') ?></span>
        </button>
    </div>
</div>